rpn:
  rpn_feat_stride: 16
  rpn_anchor_scales: !!python/tuple [8, 16, 32]
  rpn_anchor_ratios: !!python/tuple [0.5, 1, 2]
  rpn_pre_nms_topk: 12000
  rpn_post_nms_topk: 2000
  rpn_min_size: 16
  rpn_nms_thresh: 0.7
  rpn_fg_overlap: 0.7
  rpn_fg_fraction: 0.5
  rpn_bg_overlap: 0.3

rcnn:
  rcnn_feat_stride: 16
  rcnn_pooled_size: !!python/tuple [14, 14]
  rcnn_num_classes: 21
  rcnn_bbox_stds: !!python/tuple [0.1, 0.1, 0.2, 0.2]
  rcnn_fg_fraction: 0.25
  rcnn_fg_overlap: 0.5

train_param:
  net_fixed_params: ['conv0', 'stage1', 'stage2',
                     'stage3_unit2', 'stage3_unit3', 'stage3_unit4',
                     'stage3_unit5', 'stage3_unit6', 'stage3_unit7',
                     'stage3_unit8', 'stage3_unit9', 'stage3_unit10', 'stage3_unit11'
                     'gamma', 'beta']
  is_rcnn_top_bin: False

transform:
  img_pixel_means: !!python/tuple [0.0, 0.0, 0.0]
  img_pixel_stds: !!python/tuple [1.0, 1.0, 1.0]