rpn:
  rpn_feat_stride: 16
  rcnn_feat_stride: 16
  rcnn_pooled_size: !!python/tuple [7, 7]

train_param:
  net_fixed_params: ['vgg0_conv0_', 'vgg0_conv7', 'vgg0_conv8', 'vgg0_conv9']
  is_rcnn_top_bin: False

transform:
  img_pixel_means: !!python/tuple [123.68, 116.779, 103.939]
  img_pixel_stds: !!python/tuple [1.0, 1.0, 1.0]